interface Country {
    name: string;
    currency: string;
    code: string;
    symbol: string;
    flag: string;
    callingCode: string;
    region: string;
    subRegion: string;
  }
  
  export const countries: Country[] = [
    {
      name: 'Afghanistan',
      currency: 'AFN',
      code: 'AF',
      symbol: '؋',
      flag: '🇦🇫',
      callingCode: '+93',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Albania',
      currency: 'ALL',
      code: 'AL',
      symbol: 'L',
      flag: '🇦🇱',
      callingCode: '+355',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Algeria',
      currency: 'DZD',
      code: 'DZ',
      symbol: 'د.ج',
      flag: '🇩🇿',
      callingCode: '+213',
      region: 'Africa',
      subRegion: 'Northern Africa',
    },
    {
      name: 'Andorra',
      currency: 'EUR',
      code: 'AD',
      symbol: '€',
      flag: '🇦🇩',
      callingCode: '+376',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Angola',
      currency: 'AOA',
      code: 'AO',
      symbol: 'Kz',
      flag: '🇦🇴',
      callingCode: '+244',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Antigua and Barbuda',
      currency: 'XCD',
      code: 'AG',
      symbol: '$',
      flag: '🇦🇬',
      callingCode: '+1268',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Argentina',
      currency: 'ARS',
      code: 'AR',
      symbol: '$',
      flag: '🇦🇷',
      callingCode: '+54',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Armenia',
      currency: 'AMD',
      code: 'AM',
      symbol: '֏',
      flag: '🇦🇲',
      callingCode: '+374',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Australia',
      currency: 'AUD',
      code: 'AU',
      symbol: '$',
      flag: '🇦🇺',
      callingCode: '+61',
      region: 'Oceania',
      subRegion: 'Australia',
    },
    {
      name: 'Austria',
      currency: 'EUR',
      code: 'AT',
      symbol: '€',
      flag: '🇦🇹',
      callingCode: '+43',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Azerbaijan',
      currency: 'AZN',
      code: 'AZ',
      symbol: '₼',
      flag: '🇦🇿',
      callingCode: '+994',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Bahamas',
      currency: 'BSD',
      code: 'BS',
      symbol: '$',
      flag: '🇧🇸',
      callingCode: '+1242',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Bahrain',
      currency: 'BHD',
      code: 'BH',
      symbol: '.د.ب',
      flag: '🇧🇭',
      callingCode: '+973',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Bangladesh',
      currency: 'BDT',
      code: 'BD',
      symbol: '৳',
      flag: '🇧🇩',
      callingCode: '+880',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Barbados',
      currency: 'BBD',
      code: 'BB',
      symbol: '$',
      flag: '🇧🇧',
      callingCode: '+1246',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Belarus',
      currency: 'BYN',
      code: 'BY',
      symbol: 'Br',
      flag: '🇧🇾',
      callingCode: '+375',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Belgium',
      currency: 'EUR',
      code: 'BE',
      symbol: '€',
      flag: '🇧🇪',
      callingCode: '+32',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Belize',
      currency: 'BZD',
      code: 'BZ',
      symbol: '$',
      flag: '🇧🇿',
      callingCode: '+501',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Benin',
      currency: 'XOF',
      code: 'BJ',
      symbol: 'Fr',
      flag: '🇧🇯',
      callingCode: '+229',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Bhutan',
      currency: 'BTN',
      code: 'BT',
      symbol: 'Nu.',
      flag: '🇧🇹',
      callingCode: '+975',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Bolivia',
      currency: 'BOB',
      code: 'BO',
      symbol: 'Bs.',
      flag: '🇧🇴',
      callingCode: '+591',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Bosnia and Herzegovina',
      currency: 'BAM',
      code: 'BA',
      symbol: 'KM',
      flag: '🇧🇦',
      callingCode: '+387',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Botswana',
      currency: 'BWP',
      code: 'BW',
      symbol: 'P',
      flag: '🇧🇼',
      callingCode: '+267',
      region: 'Africa',
      subRegion: 'Southern Africa',
    },
    {
      name: 'Brazil',
      currency: 'BRL',
      code: 'BR',
      symbol: 'R$',
      flag: '🇧🇷',
      callingCode: '+55',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Brunei',
      currency: 'BND',
      code: 'BN',
      symbol: '$',
      flag: '🇧🇳',
      callingCode: '+673',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Bulgaria',
      currency: 'BGN',
      code: 'BG',
      symbol: 'лв',
      flag: '🇧🇬',
      callingCode: '+359',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Burkina Faso',
      currency: 'XOF',
      code: 'BF',
      symbol: 'Fr',
      flag: '🇧🇫',
      callingCode: '+226',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Burundi',
      currency: 'BIF',
      code: 'BI',
      symbol: 'Fr',
      flag: '🇧🇮',
      callingCode: '+257',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Cabo Verde',
      currency: 'CVE',
      code: 'CV',
      symbol: '$',
      flag: '🇨🇻',
      callingCode: '+238',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Cambodia',
      currency: 'KHR',
      code: 'KH',
      symbol: '៛',
      flag: '🇰🇭',
      callingCode: '+855',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Cameroon',
      currency: 'XAF',
      code: 'CM',
      symbol: 'Fr',
      flag: '🇨🇲',
      callingCode: '+237',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Canada',
      currency: 'CAD',
      code: 'CA',
      symbol: '$',
      flag: '🇨🇦',
      callingCode: '+1',
      region: 'Americas',
      subRegion: 'Northern America',
    },
    {
      name: 'Central African Republic',
      currency: 'XAF',
      code: 'CF',
      symbol: 'Fr',
      flag: '🇨🇫',
      callingCode: '+236',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Chad',
      currency: 'XAF',
      code: 'TD',
      symbol: 'Fr',
      flag: '🇹🇩',
      callingCode: '+235',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Chile',
      currency: 'CLP',
      code: 'CL',
      symbol: '$',
      flag: '🇨🇱',
      callingCode: '+56',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'China',
      currency: 'CNY',
      code: 'CN',
      symbol: '¥',
      flag: '🇨🇳',
      callingCode: '+86',
      region: 'Asia',
      subRegion: 'Eastern Asia',
    },
    {
      name: 'Colombia',
      currency: 'COP',
      code: 'CO',
      symbol: '$',
      flag: '🇨🇴',
      callingCode: '+57',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Comoros',
      currency: 'KMF',
      code: 'KM',
      symbol: 'Fr',
      flag: '🇰🇲',
      callingCode: '+269',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Congo',
      currency: 'XAF',
      code: 'CG',
      symbol: 'Fr',
      flag: '🇨🇬',
      callingCode: '+242',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Costa Rica',
      currency: 'CRC',
      code: 'CR',
      symbol: '₡',
      flag: '🇨🇷',
      callingCode: '+506',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Croatia',
      currency: 'HRK',
      code: 'HR',
      symbol: 'kn',
      flag: '🇭🇷',
      callingCode: '+385',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Cuba',
      currency: 'CUP',
      code: 'CU',
      symbol: '$',
      flag: '🇨🇺',
      callingCode: '+53',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Cyprus',
      currency: 'EUR',
      code: 'CY',
      symbol: '€',
      flag: '🇨🇾',
      callingCode: '+357',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Czech Republic',
      currency: 'CZK',
      code: 'CZ',
      symbol: 'Kč',
      flag: '🇨🇿',
      callingCode: '+420',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Denmark',
      currency: 'DKK',
      code: 'DK',
      symbol: 'kr',
      flag: '🇩🇰',
      callingCode: '+45',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'Djibouti',
      currency: 'DJF',
      code: 'DJ',
      symbol: 'Fr',
      flag: '🇩🇯',
      callingCode: '+253',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Dominica',
      currency: 'XCD',
      code: 'DM',
      symbol: '$',
      flag: '🇩🇲',
      callingCode: '+1767',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Dominican Republic',
      currency: 'DOP',
      code: 'DO',
      symbol: '$',
      flag: '🇩🇴',
      callingCode: '+1',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Ecuador',
      currency: 'USD',
      code: 'EC',
      symbol: '$',
      flag: '🇪🇨',
      callingCode: '+593',
      region: 'Americas',
      subRegion: 'Southern America',
    },
    {
      name: 'Egypt',
      currency: 'EGP',
      code: 'EG',
      symbol: 'E£',
      flag: '🇪🇬',
      callingCode: '+20',
      region: 'Africa',
      subRegion: 'Northern Africa',
    },
    {
      name: 'El Salvador',
      currency: 'USD',
      code: 'SV',
      symbol: '$',
      flag: '🇸🇻',
      callingCode: '+503',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Equatorial Guinea',
      currency: 'XAF',
      code: 'GQ',
      symbol: 'Fr',
      flag: '🇬🇶',
      callingCode: '+240',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Eritrea',
      currency: 'ERN',
      code: 'ER',
      symbol: 'Nfk',
      flag: '🇪🇷',
      callingCode: '+291',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Estonia',
      currency: 'EUR',
      code: 'EE',
      symbol: '€',
      flag: '🇪🇪',
      callingCode: '+372',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'Eswatini',
      currency: 'SZL',
      code: 'SZ',
      symbol: 'L',
      flag: '🇸🇿',
      callingCode: '+268',
      region: 'Africa',
      subRegion: 'Southern Africa',
    },
    {
      name: 'Ethiopia',
      currency: 'ETB',
      code: 'ET',
      symbol: 'Br',
      flag: '🇪🇹',
      callingCode: '+251',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Fiji',
      currency: 'FJD',
      code: 'FJ',
      symbol: '$',
      flag: '🇫🇯',
      callingCode: '+679',
      region: 'Oceania',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Finland',
      currency: 'EUR',
      code: 'FI',
      symbol: '€',
      flag: '🇫🇮',
      callingCode: '+358',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'France',
      currency: 'EUR',
      code: 'FR',
      symbol: '€',
      flag: '🇫🇷',
      callingCode: '+33',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Gabon',
      currency: 'XAF',
      code: 'GA',
      symbol: 'Fr',
      flag: '🇬🇦',
      callingCode: '+241',
      region: 'Africa',
      subRegion: 'Middle Africa',
    },
    {
      name: 'Gambia',
      currency: 'GMD',
      code: 'GM',
      symbol: 'D',
      flag: '🇬🇲',
      callingCode: '+220',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Georgia',
      currency: 'GEL',
      code: 'GE',
      symbol: '₾',
      flag: '🇬🇪',
      callingCode: '+995',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Germany',
      currency: 'EUR',
      code: 'DE',
      symbol: '€',
      flag: '🇩🇪',
      callingCode: '+49',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Ghana',
      currency: 'GHS',
      code: 'GH',
      symbol: '₵',
      flag: '🇬🇭',
      callingCode: '+233',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Greece',
      currency: 'EUR',
      code: 'GR',
      symbol: '€',
      flag: '🇬🇷',
      callingCode: '+30',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Germany',
      currency: 'EUR',
      code: 'DE',
      symbol: '€',
      flag: '🇩🇪',
      callingCode: '+49',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Grenada',
      currency: 'XCD',
      code: 'GD',
      symbol: '$',
      flag: '🇬🇩',
      callingCode: '+1473',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Guatemala',
      currency: 'GTQ',
      code: 'GT',
      symbol: 'Q',
      flag: '🇬🇹',
      callingCode: '+502',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Guinea',
      currency: 'GNF',
      code: 'GN',
      symbol: 'Fr',
      flag: '🇬🇳',
      callingCode: '+224',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Guinea-Bissau',
      currency: 'XOF',
      code: 'GW',
      symbol: 'Fr',
      flag: '🇬🇼',
      callingCode: '+245',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Guyana',
      currency: 'GYD',
      code: 'GY',
      symbol: '$',
      flag: '🇬🇾',
      callingCode: '+592',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Haiti',
      currency: 'HTG',
      code: 'HT',
      symbol: 'G',
      flag: '🇭🇹',
      callingCode: '+509',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Honduras',
      currency: 'HNL',
      code: 'HN',
      symbol: 'L',
      flag: '🇭🇳',
      callingCode: '+504',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Hungary',
      currency: 'HUF',
      code: 'HU',
      symbol: 'Ft',
      flag: '🇭🇺',
      callingCode: '+36',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Iceland',
      currency: 'ISK',
      code: 'IS',
      symbol: 'kr',
      flag: '🇮🇸',
      callingCode: '+354',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'India',
      currency: 'INR',
      code: 'IN',
      symbol: '₹',
      flag: '🇮🇳',
      callingCode: '+91',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Indonesia',
      currency: 'IDR',
      code: 'ID',
      symbol: 'Rp',
      flag: '🇮🇩',
      callingCode: '+62',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Iran',
      currency: 'IRR',
      code: 'IR',
      symbol: '﷼',
      flag: '🇮🇷',
      callingCode: '+98',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Iraq',
      currency: 'IQD',
      code: 'IQ',
      symbol: 'ع.د',
      flag: '🇮🇶',
      callingCode: '+964',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Ireland',
      currency: 'EUR',
      code: 'IE',
      symbol: '€',
      flag: '🇮🇪',
      callingCode: '+353',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
  
    {
      name: 'Israel',
      currency: 'ILS',
      code: 'IL',
      symbol: '₪',
      flag: '🇮🇱',
      callingCode: '+972',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Italy',
      currency: 'EUR',
      code: 'IT',
      symbol: '€',
      flag: '🇮🇹',
      callingCode: '+39',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
  
    {
      name: 'Jamaica',
      currency: 'JMD',
      code: 'JM',
      symbol: '$',
      flag: '🇯🇲',
      callingCode: '+1876',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Japan',
      currency: 'JPY',
      code: 'JP',
      symbol: '¥',
      flag: '🇯🇵',
      callingCode: '+81',
      region: 'Asia',
      subRegion: 'Eastern Asia',
    },
    {
      name: 'Jordan',
      currency: 'JOD',
      code: 'JO',
      symbol: 'د.ا',
      flag: '🇯🇴',
      callingCode: '+962',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Kazakhstan',
      currency: 'KZT',
      code: 'KZ',
      symbol: '₸',
      flag: '🇰🇿',
      callingCode: '+7',
      region: 'Asia',
      subRegion: 'Central Asia',
    },
    {
      name: 'Kenya',
      currency: 'KES',
      code: 'KE',
      symbol: 'Sh',
      flag: '🇰🇪',
      callingCode: '+254',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Kiribati',
      currency: 'AUD',
      code: 'KI',
      symbol: '$',
      flag: '🇰🇮',
      callingCode: '+686',
      region: 'Oceania',
      subRegion: 'Micronesia',
    },
    {
      name: 'Kuwait',
      currency: 'KWD',
      code: 'KW',
      symbol: 'د.ك',
      flag: '🇰🇼',
      callingCode: '+965',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Kyrgyzstan',
      currency: 'KGS',
      code: 'KG',
      symbol: 'лв',
      flag: '🇰🇬',
      callingCode: '+996',
      region: 'Asia',
      subRegion: 'Central Asia',
    },
  
    {
      name: 'Laos',
      currency: 'LAK',
      code: 'LA',
      symbol: '₭',
      flag: '🇱🇦',
      callingCode: '+856',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Latvia',
      currency: 'EUR',
      code: 'LV',
      symbol: '€',
      flag: '🇱🇻',
      callingCode: '+371',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'Lebanon',
      currency: 'LBP',
      code: 'LB',
      symbol: 'ل.ل',
      flag: '🇱🇧',
      callingCode: '+961',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Lesotho',
      currency: 'LSL',
      code: 'LS',
      symbol: 'L',
      flag: '🇱🇸',
      callingCode: '+266',
      region: 'Africa',
      subRegion: 'Southern Africa',
    },
    {
      name: 'Liberia',
      currency: 'LRD',
      code: 'LR',
      symbol: '$',
      flag: '🇱🇷',
      callingCode: '+231',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Libya',
      currency: 'LYD',
      code: 'LY',
      symbol: 'ل.د',
      flag: '🇱🇾',
      callingCode: '+218',
      region: 'Africa',
      subRegion: 'Northern Africa',
    },
    {
      name: 'Liechtenstein',
      currency: 'CHF',
      code: 'LI',
      symbol: 'Fr',
      flag: '🇱🇮',
      callingCode: '+423',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Lithuania',
      currency: 'EUR',
      code: 'LT',
      symbol: '€',
      flag: '🇱🇹',
      callingCode: '+370',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'Luxembourg',
      currency: 'EUR',
      code: 'LU',
      symbol: '€',
      flag: '🇱🇺',
      callingCode: '+352',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    // complete for countries name  starting with M
    {
      name: 'Madagascar',
      currency: 'MGA',
      code: 'MG',
      symbol: 'Ar',
      flag: '🇲🇬',
      callingCode: '+261',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Malawi',
      currency: 'MWK',
      code: 'MW',
      symbol: 'MK',
      flag: '🇲🇼',
      callingCode: '+265',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Malaysia',
      currency: 'MYR',
      code: 'MY',
      symbol: 'RM',
      flag: '🇲🇾',
      callingCode: '+60',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Maldives',
      currency: 'MVR',
      code: 'MV',
      symbol: 'Rf',
      flag: '🇲🇻',
      callingCode: '+960',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Mali',
      currency: 'XOF',
      code: 'ML',
      symbol: 'Fr',
      flag: '🇲🇱',
      callingCode: '+223',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Malta',
      currency: 'EUR',
      code: 'MT',
      symbol: '€',
      flag: '🇲🇹',
      callingCode: '+356',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Marshall Islands',
      currency: 'USD',
      code: 'MH',
      symbol: '$',
      flag: '🇲🇭',
      callingCode: '+692',
      region: 'Oceania',
      subRegion: 'Micronesia',
    },
    {
      name: 'Mauritania',
      currency: 'MRU',
      code: 'MR',
      symbol: 'UM',
      flag: '🇲🇷',
      callingCode: '+222',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Mauritania',
      currency: 'MRU',
      code: 'MR',
      symbol: 'UM',
      flag: '🇲🇷',
      callingCode: '+222',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Mauritius',
      currency: 'MUR',
      code: 'MU',
      symbol: '₨',
      flag: '🇲🇺',
      callingCode: '+230',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Mexico',
      currency: 'MXN',
      code: 'MX',
      symbol: '$',
      flag: '🇲🇽',
      callingCode: '+52',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Micronesia',
      currency: 'USD',
      code: 'FM',
      symbol: '$',
      flag: '🇫🇲',
      callingCode: '+691',
      region: 'Oceania',
      subRegion: 'Micronesia',
    },
    {
      name: 'Moldova',
      currency: 'MDL',
      code: 'MD',
      symbol: 'L',
      flag: '🇲🇩',
      callingCode: '+373',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Monaco',
      currency: 'EUR',
      code: 'MC',
      symbol: '€',
      flag: '🇲🇨',
      callingCode: '+377',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Mongolia',
      currency: 'MNT',
      code: 'MN',
      symbol: '₮',
      flag: '🇲🇳',
      callingCode: '+976',
      region: 'Asia',
      subRegion: 'Eastern Asia',
    },
    {
      name: 'Montenegro',
      currency: 'EUR',
      code: 'ME',
      symbol: '€',
      flag: '🇲🇪',
      callingCode: '+382',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Morocco',
      currency: 'MAD',
      code: 'MA',
      symbol: 'د.م.',
      flag: '🇲🇦',
      callingCode: '+212',
      region: 'Africa',
      subRegion: 'Northern Africa',
    },
    {
      name: 'Mozambique',
      currency: 'MZN',
      code: 'MZ',
      symbol: 'MT',
      flag: '🇲🇿',
      callingCode: '+258',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Myanmar',
      currency: 'MMK',
      code: 'MM',
      symbol: 'K',
      flag: '🇲🇲',
      callingCode: '+95',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Namibia',
      currency: 'NAD',
      code: 'NA',
      symbol: '$',
      flag: '🇳🇦',
      callingCode: '+264',
      region: 'Africa',
      subRegion: 'Southern Africa',
    },
    {
      name: 'Nauru',
      currency: 'AUD',
      code: 'NR',
      symbol: '$',
      flag: '🇳🇷',
      callingCode: '+674',
      region: 'Oceania',
      subRegion: 'Micronesia',
    },
    {
      name: 'Nepal',
      currency: 'NPR',
      code: 'NP',
      symbol: '₨',
      flag: '🇳🇵',
      callingCode: '+977',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Netherlands',
      currency: 'EUR',
      code: 'NL',
      symbol: '€',
      flag: '🇳🇱',
      callingCode: '+31',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'New Zealand',
      currency: 'NZD',
      code: 'NZ',
      symbol: '$',
      flag: '🇳🇿',
      callingCode: '+64',
      region: 'Oceania',
      subRegion: 'Australia and New Zealand',
    },
    {
      name: 'Nicaragua',
      currency: 'NIO',
      code: 'NI',
      symbol: 'C$',
      flag: '🇳🇮',
      callingCode: '+505',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Niger',
      currency: 'XOF',
      code: 'NE',
      symbol: 'Fr',
      flag: '🇳🇪',
      callingCode: '+227',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Nigeria',
      currency: 'NGN',
      code: 'NG',
      symbol: '₦',
      flag: '🇳🇬',
      callingCode: '+234',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'North Korea',
      currency: 'KPW',
      code: 'KP',
      symbol: '₩',
      flag: '🇰🇵',
      callingCode: '+850',
      region: 'Asia',
      subRegion: 'Eastern Asia',
    },
    {
      name: 'North Macedonia',
      currency: 'MKD',
      code: 'MK',
      symbol: 'ден',
      flag: '🇲🇰',
      callingCode: '+389',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Norway',
      currency: 'NOK',
      code: 'NO',
      symbol: 'kr',
      flag: '🇳🇴',
      callingCode: '+47',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'Oman',
      currency: 'OMR',
      code: 'OM',
      symbol: 'ر.ع.',
      flag: '🇴🇲',
      callingCode: '+968',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Pakistan',
      currency: 'PKR',
      code: 'PK',
      symbol: '₨',
      flag: '🇵🇰',
      callingCode: '+92',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Palau',
      currency: 'USD',
      code: 'PW',
      symbol: '$',
      flag: '🇵🇼',
      callingCode: '+680',
      region: 'Oceania',
      subRegion: 'Micronesia',
    },
    {
      name: 'Palestine',
      currency: 'ILS',
      code: 'PS',
      symbol: '₪',
      flag: '🇵🇸',
      callingCode: '+970',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Panama',
      currency: 'PAB',
      code: 'PA',
      symbol: 'B/.',
      flag: '🇵🇦',
      callingCode: '+507',
      region: 'Americas',
      subRegion: 'Central America',
    },
    {
      name: 'Papua New Guinea',
      currency: 'PGK',
      code: 'PG',
      symbol: 'K',
      flag: '🇵🇬',
      callingCode: '+675',
      region: 'Oceania',
      subRegion: 'Melanesia',
    },
    {
      name: 'Paraguay',
      currency: 'PYG',
      code: 'PY',
      symbol: '₲',
      flag: '🇵🇾',
      callingCode: '+595',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Peru',
      currency: 'PEN',
      code: 'PE',
      symbol: 'S/.',
      flag: '🇵🇪',
      callingCode: '+51',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Philippines',
      currency: 'PHP',
      code: 'PH',
      symbol: '₱',
      flag: '🇵🇭',
      callingCode: '+63',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Poland',
      currency: 'PLN',
      code: 'PL',
      symbol: 'zł',
      flag: '🇵🇱',
      callingCode: '+48',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Portugal',
      currency: 'EUR',
      code: 'PT',
      symbol: '€',
      flag: '🇵🇹',
      callingCode: '+351',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Qatar',
      currency: 'QAR',
      code: 'QA',
      symbol: 'ر.ق',
      flag: '🇶🇦',
      callingCode: '+974',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Romania',
      currency: 'RON',
      code: 'RO',
      symbol: 'lei',
      flag: '🇷🇴',
      callingCode: '+40',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Russia',
      currency: 'RUB',
      code: 'RU',
      symbol: '₽',
      flag: '🇷🇺',
      callingCode: '+7',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Rwanda',
      currency: 'RWF',
      code: 'RW',
      symbol: 'Fr',
      flag: '🇷🇼',
      callingCode: '+250',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Saint Kitts and Nevis',
      currency: 'XCD',
      code: 'KN',
      symbol: '$',
      flag: '🇰🇳',
      callingCode: '+1-869',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Saint Lucia',
      currency: 'XCD',
      code: 'LC',
      symbol: '$',
      flag: '🇱🇨',
      callingCode: '+1-758',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      currency: 'XCD',
      code: 'VC',
      symbol: '$',
      flag: '🇻🇨',
      callingCode: '+1-784',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Samoa',
      currency: 'WST',
      code: 'WS',
      symbol: 'T',
      flag: '🇼🇸',
      callingCode: '+685',
      region: 'Oceania',
      subRegion: 'Polynesia',
    },
    {
      name: 'San Marino',
      currency: 'EUR',
      code: 'SM',
      symbol: '€',
      flag: '🇸🇲',
      callingCode: '+378',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Sao Tome and Principe',
      currency: 'STN',
      code: 'ST',
      symbol: 'Db',
      flag: '🇸🇹',
      callingCode: '+239',
      region: 'Africa',
      subRegion: 'Central Africa',
    },
    {
      name: 'Saudi Arabia',
      currency: 'SAR',
      code: 'SA',
      symbol: 'ر.س',
      flag: '🇸🇦',
      callingCode: '+966',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Senegal',
      currency: 'XOF',
      code: 'SN',
      symbol: 'Fr',
      flag: '🇸🇳',
      callingCode: '+221',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Serbia',
      currency: 'RSD',
      code: 'RS',
      symbol: 'дин.',
      flag: '🇷🇸',
      callingCode: '+381',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Seychelles',
      currency: 'SCR',
      code: 'SC',
      symbol: '₨',
      flag: '🇸🇨',
      callingCode: '+248',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Sierra Leone',
      currency: 'SLL',
      code: 'SL',
      symbol: 'Le',
      flag: '🇸🇱',
      callingCode: '+232',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Singapore',
      currency: 'SGD',
      code: 'SG',
      symbol: '$',
      flag: '🇸🇬',
      callingCode: '+65',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Slovakia',
      currency: 'EUR',
      code: 'SK',
      symbol: '€',
      flag: '🇸🇰',
      callingCode: '+421',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'Slovenia',
      currency: 'EUR',
      code: 'SI',
      symbol: '€',
      flag: '🇸🇮',
      callingCode: '+386',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Solomon Islands',
      currency: 'SBD',
      code: 'SB',
      symbol: '$',
      flag: '🇸🇧',
      callingCode: '+677',
      region: 'Oceania',
      subRegion: 'Melanesia',
    },
    {
      name: 'Somalia',
      currency: 'SOS',
      code: 'SO',
      symbol: 'Sh',
      flag: '🇸🇴',
      callingCode: '+252',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'South Africa',
      currency: 'ZAR',
      code: 'ZA',
      symbol: 'R',
      flag: '🇿🇦',
      callingCode: '+27',
      region: 'Africa',
      subRegion: 'Southern Africa',
    },
    {
      name: 'South Korea',
      currency: 'KRW',
      code: 'KR',
      symbol: '₩',
      flag: '🇰🇷',
      callingCode: '+82',
      region: 'Asia',
      subRegion: 'Eastern Asia',
    },
    {
      name: 'South Sudan',
      currency: 'SSP',
      code: 'SS',
      symbol: '£',
      flag: '🇸🇸',
      callingCode: '+211',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Spain',
      currency: 'EUR',
      code: 'ES',
      symbol: '€',
      flag: '🇪🇸',
      callingCode: '+34',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Sri Lanka',
      currency: 'LKR',
      code: 'LK',
      symbol: '₨',
      flag: '🇱🇰',
      callingCode: '+94',
      region: 'Asia',
      subRegion: 'Southern Asia',
    },
    {
      name: 'Sudan',
      currency: 'SDG',
      code: 'SD',
      symbol: 'ج.س.',
      flag: '🇸🇩',
      callingCode: '+249',
      region: 'Africa',
      subRegion: 'Northern Africa',
    },
    {
      name: 'Suriname',
      currency: 'SRD',
      code: 'SR',
      symbol: '$',
      flag: '🇸🇷',
      callingCode: '+597',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Sweden',
      currency: 'SEK',
      code: 'SE',
      symbol: 'kr',
      flag: '🇸🇪',
      callingCode: '+46',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'Switzerland',
      currency: 'CHF',
      code: 'CH',
      symbol: 'Fr',
      flag: '🇨🇭',
      callingCode: '+41',
      region: 'Europe',
      subRegion: 'Western Europe',
    },
    {
      name: 'Syria',
      currency: 'SYP',
      code: 'SY',
      symbol: '£',
      flag: '🇸🇾',
      callingCode: '+963',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Taiwan',
      currency: 'TWD',
      code: 'TW',
      symbol: '$',
      flag: '🇹🇼',
      callingCode: '+886',
      region: 'Asia',
      subRegion: 'Eastern Asia',
    },
    {
      name: 'Tajikistan',
      currency: 'TJS',
      code: 'TJ',
      symbol: 'ЅМ',
      flag: '🇹🇯',
      callingCode: '+992',
      region: 'Asia',
      subRegion: 'Central Asia',
    },
    {
      name: 'Tanzania',
      currency: 'TZS',
      code: 'TZ',
      symbol: 'Sh',
      flag: '🇹🇿',
      callingCode: '+255',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Thailand',
      currency: 'THB',
      code: 'TH',
      symbol: '฿',
      flag: '🇹🇭',
      callingCode: '+66',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Togo',
      currency: 'XOF',
      code: 'TG',
      symbol: 'Fr',
      flag: '🇹🇬',
      callingCode: '+228',
      region: 'Africa',
      subRegion: 'Western Africa',
    },
    {
      name: 'Tonga',
      currency: 'TOP',
      code: 'TO',
      symbol: 'T$',
      flag: '🇹🇴',
      callingCode: '+676',
      region: 'Oceania',
      subRegion: 'Polynesia',
    },
    {
      name: 'Trinidad and Tobago',
      currency: 'TTD',
      code: 'TT',
      symbol: '$',
      flag: '🇹🇹',
      callingCode: '+1-868',
      region: 'Americas',
      subRegion: 'Caribbean',
    },
    {
      name: 'Tunisia',
      currency: 'TND',
      code: 'TN',
      symbol: 'د.ت',
      flag: '🇹🇳',
      callingCode: '+216',
      region: 'Africa',
      subRegion: 'Northern Africa',
    },
    {
      name: 'Turkey',
      currency: 'TRY',
      code: 'TR',
      symbol: '₺',
      flag: '🇹🇷',
      callingCode: '+90',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Turkmenistan',
      currency: 'TMT',
      code: 'TM',
      symbol: 'm',
      flag: '🇹🇲',
      callingCode: '+993',
      region: 'Asia',
      subRegion: 'Central Asia',
    },
    {
      name: 'Tuvalu',
      currency: 'AUD',
      code: 'TV',
      symbol: '$',
      flag: '🇹🇻',
      callingCode: '+688',
      region: 'Oceania',
      subRegion: 'Polynesia',
    },
    {
      name: 'Uganda',
      currency: 'UGX',
      code: 'UG',
      symbol: 'Sh',
      flag: '🇺🇬',
      callingCode: '+256',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Ukraine',
      currency: 'UAH',
      code: 'UA',
      symbol: '₴',
      flag: '🇺🇦',
      callingCode: '+380',
      region: 'Europe',
      subRegion: 'Eastern Europe',
    },
    {
      name: 'United Arab Emirates',
      currency: 'AED',
      code: 'AE',
      symbol: 'د.إ',
      flag: '🇦🇪',
      callingCode: '+971',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'United Kingdom',
      currency: 'GBP',
      code: 'GB',
      symbol: '£',
      flag: '🇬🇧',
      callingCode: '+44',
      region: 'Europe',
      subRegion: 'Northern Europe',
    },
    {
      name: 'United States',
      currency: 'USD',
      code: 'US',
      symbol: '$',
      flag: '🇺🇸',
      callingCode: '+1',
      region: 'Americas',
      subRegion: 'Northern America',
    },
    {
      name: 'Uruguay',
      currency: 'UYU',
      code: 'UY',
      symbol: '$',
      flag: '🇺🇾',
      callingCode: '+598',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Uzbekistan',
      currency: 'UZS',
      code: 'UZ',
      symbol: 'лв',
      flag: '🇺🇿',
      callingCode: '+998',
      region: 'Asia',
      subRegion: 'Central Asia',
    },
    {
      name: 'Vanuatu',
      currency: 'VUV',
      code: 'VU',
      symbol: 'Vt',
      flag: '🇻🇺',
      callingCode: '+678',
      region: 'Oceania',
      subRegion: 'Melanesia',
    },
    {
      name: 'Vatican City',
      currency: 'EUR',
      code: 'VA',
      symbol: '€',
      flag: '🇻🇦',
      callingCode: '+379',
      region: 'Europe',
      subRegion: 'Southern Europe',
    },
    {
      name: 'Venezuela',
      currency: 'VES',
      code: 'VE',
      symbol: 'Bs.',
      flag: '🇻🇪',
      callingCode: '+58',
      region: 'Americas',
      subRegion: 'South America',
    },
    {
      name: 'Vietnam',
      currency: 'VND',
      code: 'VN',
      symbol: '₫',
      flag: '🇻🇳',
      callingCode: '+84',
      region: 'Asia',
      subRegion: 'South-Eastern Asia',
    },
    {
      name: 'Yemen',
      currency: 'YER',
      code: 'YE',
      symbol: '﷼',
      flag: '🇾🇪',
      callingCode: '+967',
      region: 'Asia',
      subRegion: 'Western Asia',
    },
    {
      name: 'Zambia',
      currency: 'ZMW',
      code: 'ZM',
      symbol: 'ZK',
      flag: '🇿🇲',
      callingCode: '+260',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
    {
      name: 'Zimbabwe',
      currency: 'ZWL',
      code: 'ZW',
      symbol: '$',
      flag: '🇿🇼',
      callingCode: '+263',
      region: 'Africa',
      subRegion: 'Eastern Africa',
    },
  ];
  